from typing import Protocol
from app.ocr.types import OcrRequest, OcrPageResult


class OcrBackend(Protocol):
    def initialize(self): ...
    def recognize(self, request: OcrRequest, device: str) -> OcrPageResult: ...
    def capabilities(self) -> dict: ...
    def shutdown(self): ...
